---
title: "CSMPL Human Data Analysis 20221010"
author: "Dan Conroy-Beam"
date: "2022-10-10"
output: html_document
---



######Packages######
```{r}
library(ggplot2)
library(lmerTest)
library(reshape2)
```





######Parameters######
```{r}
#Save figures?
sf<-1

```







######Functions######
```{r}

#Attraction calculation#
mvcalc<-function(ideal,traits){
  #ideal is ideal preferences
  #traits is actual trait values

  #Calculates the Euclidean distance between the agent's preferences and each mate's traits
  #Transforms this distance such that positive values are more attractive by multiplying by -1 and adding 1 plus the maximum possible Euclidean distance
  mv<-apply(traits,1,function(x) 10*(-1*(dist(rbind(ideal,x)))+sqrt(10^2*16))/sqrt(10^2*16))

  
  return(mv)
  
}

```





######Load Data######
```{r}
#Load the data
data<-read.csv(file="Human Data/Processed Data/CAREER1 PROCESSED Data 01172020 104258.csv")

males<-data[data$sex==1,]
females<-data[data$sex==0,]


```






######Data Analysis######
```{r}

#Calculate aggregate preferences
avPrefs<-colMeans(rbind(males[,235:250],females[,235:250]))
fPrefs<-colMeans(females[,235:250])
mPrefs<-colMeans(males[,235:250])


#Mate Value Calculation#

#Males
#Calculate how attracted each male is to each female according to consensual preferences, sex-typical preferences, or individual-level preferences

avMaleAttMatrix<-t(apply(males,1,function(q) mvcalc(avPrefs,females[,c(345:360)])))

colnames(avMaleAttMatrix)<-females$PIN
rownames(avMaleAttMatrix)<-males$PIN

sexMaleAttMatrix<-t(apply(males,1,function(q) mvcalc(mPrefs,females[,c(345:360)])))

colnames(sexMaleAttMatrix)<-females$PIN
rownames(sexMaleAttMatrix)<-males$PIN

indMaleAttMatrix<-t(apply(males,1,function(q) mvcalc(q[235:250],females[,c(345:360)])))

colnames(indMaleAttMatrix)<-females$PIN
rownames(indMaleAttMatrix)<-males$PIN


#Females
#Calculate how attracted each female is to each male according to consensual preferences, sex-typical preferences, or individual-level preferences

avFemaleAttMatrix<-t(apply(females,1,function(q) mvcalc(avPrefs,males[,c(345:360)])))

colnames(avFemaleAttMatrix)<-males$PIN
rownames(avFemaleAttMatrix)<-females$PIN

sexFemaleAttMatrix<-t(apply(females,1,function(q) mvcalc(mPrefs,males[,c(345:360)])))

colnames(sexFemaleAttMatrix)<-males$PIN
rownames(sexFemaleAttMatrix)<-females$PIN

indFemaleAttMatrix<-t(apply(females,1,function(q) mvcalc(q[235:250],males[,c(345:360)])))

colnames(indFemaleAttMatrix)<-males$PIN
rownames(indFemaleAttMatrix)<-females$PIN


###Mate Choice###

#Consensual Preferences#
#Mate choice follows Gale-Shapley Algorithm because RAM requires unique mutual interest between agents

#A blank dataframe for storing the paired couples
avPairs<-matrix(,1,(ncol(males)+ncol(females)))
avPairs<-as.data.frame(avPairs)

#Name the avPairs dataframe for cbinding
colnames(avPairs)<-c(colnames(females),colnames(males))

#A vector of male agents' partners
mPartner<-matrix(0,nrow(males),1)

#A vector of female agents' partners
fPartner<-matrix(0,nrow(females),1)

#A matrix of females have already rejected each male
mRejected<-matrix(0,nrow(males),nrow(females))

#Loops as long as some male is still unpaired
while(sum(mPartner==0,na.rm=T)>0){

  #Selects the first unpaired male
  focalMale<-which(mPartner==0)[1]

  #Pulls out his attractions
  focalMaleAtts<-avMaleAttMatrix[focalMale,]

  #Determines which females have already rejected him
  focalMaleRejections<-mRejected[focalMale,]

  #If there is still a female left who has not rejected the focal male...
  if(sum(focalMaleRejections)<nrow(females)){

    #Sets the attractiveness of each female who has rejected the focal male to 0
    focalMaleAtts[focalMaleRejections==1]<-0

    #Determines which of the remaining females he is most attracted to
    femaleChosen<-which(focalMaleAtts==max(focalMaleAtts))[1]

    #If she is single...
    if(fPartner[femaleChosen]==0){
      #She provisionally pairs with him
      fPartner[femaleChosen]<-focalMale

      #And he provisionally pairs with her
      mPartner[focalMale]<-femaleChosen

      #If the chosen female is not single, she compares the attractiveness of the focal male to her current partner...
    } else if(avFemaleAttMatrix[femaleChosen,focalMale]>avFemaleAttMatrix[femaleChosen,fPartner[femaleChosen]]){
      #If the focal male is more attractive to the chosen female than her current partner...

      #The chosen female rejects her current partner
      mRejected[fPartner[femaleChosen],femaleChosen]<-1

      #And he becomes single
      mPartner[fPartner[femaleChosen]]<-0

      #And the focal male and the chosen female provisionally pair
      mPartner[focalMale]<-femaleChosen
      fPartner[femaleChosen]<-focalMale
    } else{
      #If the focal male is not more attractive to the chosen female than her current partner, the chosen female rejects the focal male
      mRejected[focalMale,femaleChosen]<-1
    }
  } else{
    #If there is no female who has yet to reject the male, have him abandon search
    mPartner[focalMale]<-NA
  }
}

mPartner<-mPartner[is.na(mPartner)==F]

#Loop through males' choices
for(p in 1:length(mPartner)){
  #Pair each male with his chosen female
  avPairs<-rbind(avPairs,cbind(females[mPartner[p],],males[p,]))
}

#Remove the row of NAs from the avPairs dataframe
avPairs<-avPairs[-1,]



#Sex-Typical Preferences#
#Mate choice follows Gale-Shapley Algorithm because RAM requires unique mutual interest between agents

#A blank dataframe for storing the paired couples
sexPairs<-matrix(,1,(ncol(males)+ncol(females)))
sexPairs<-as.data.frame(sexPairs)

#Name the sexPairs dataframe for cbinding
colnames(sexPairs)<-c(colnames(females),colnames(males))

#A vector of male agents' partners
mPartner<-matrix(0,nrow(males),1)

#A vector of female agents' partners
fPartner<-matrix(0,nrow(females),1)

#A matrix of females have already rejected each male
mRejected<-matrix(0,nrow(males),nrow(females))

#Loops as long as some male is still unpaired
while(sum(mPartner==0,na.rm=T)>0){

  #Selects the first unpaired male
  focalMale<-which(mPartner==0)[1]

  #Pulls out his attractions
  focalMaleAtts<-sexMaleAttMatrix[focalMale,]

  #Determines which females have already rejected him
  focalMaleRejections<-mRejected[focalMale,]

  #If there is still a female left who has not rejected the focal male...
  if(sum(focalMaleRejections)<nrow(females)){

    #Sets the attractiveness of each female who has rejected the focal male to 0
    focalMaleAtts[focalMaleRejections==1]<-0

    #Determines which of the remaining females he is most attracted to
    femaleChosen<-which(focalMaleAtts==max(focalMaleAtts))[1]

    #If she is single...
    if(fPartner[femaleChosen]==0){
      #She provisionally pairs with him
      fPartner[femaleChosen]<-focalMale

      #And he provisionally pairs with her
      mPartner[focalMale]<-femaleChosen

      #If the chosen female is not single, she compares the attractiveness of the focal male to her current partner...
    } else if(sexFemaleAttMatrix[femaleChosen,focalMale]>sexFemaleAttMatrix[femaleChosen,fPartner[femaleChosen]]){
      #If the focal male is more attractive to the chosen female than her current partner...

      #The chosen female rejects her current partner
      mRejected[fPartner[femaleChosen],femaleChosen]<-1

      #And he becomes single
      mPartner[fPartner[femaleChosen]]<-0

      #And the focal male and the chosen female provisionally pair
      mPartner[focalMale]<-femaleChosen
      fPartner[femaleChosen]<-focalMale
    } else{
      #If the focal male is not more attractive to the chosen female than her current partner, the chosen female rejects the focal male
      mRejected[focalMale,femaleChosen]<-1
    }
  } else{
    #If there is no female who has yet to reject the male, have him abandon search
    mPartner[focalMale]<-NA
  }
}

mPartner<-mPartner[is.na(mPartner)==F]

#Loop through males' choices
for(p in 1:length(mPartner)){
  #Pair each male with his chosen female
  sexPairs<-rbind(sexPairs,cbind(females[mPartner[p],],males[p,]))
}

#Remove the row of NAs from the sexPairs dataframe
sexPairs<-sexPairs[-1,]



#Individual Preferences#

#A blank dataframe for storing the paired couples
indPairs<-matrix(,1,(ncol(males)+ncol(females)))
indPairs<-as.data.frame(indPairs)

#Name the indPairs dataframe for cbinding
colnames(indPairs)<-c(colnames(females),colnames(males))

#A matrix for storing how much investment each agent sends to each potential mate
#Start with how attracted each agent is to each potential mate
maleInvestPropS<-indMaleAttMatrix
femaleInvestPropS<-indFemaleAttMatrix

maleInvestPropS<-t(apply(maleInvestPropS,1,function(x) x*(10/sum(x))))
femaleInvestPropS<-t(apply(femaleInvestPropS,1,function(x) x*(10/sum(x))))

#Loop through 100 timesteps for courtship
for(c in 1:100){
  #How much investment each male agent received from each female agent in the previous timestep
  maleInvestPropR<-t(femaleInvestPropS)
  
  #How much investment each female agent received from each male agent in the previous timestep
  femaleInvestPropR<-t(maleInvestPropS)
  
  #Calculate how much investment each agent will send in this round.
  #Investment after the first round is proportional to the mutual investment in the previous round
  maleInvestPropS<-maleInvestPropS*maleInvestPropR
  femaleInvestPropS<-femaleInvestPropS*femaleInvestPropR
  
  maleInvestPropS<-t(apply(maleInvestPropS,1,function(x) x*(10/sum(x))))
  femaleInvestPropS<-t(apply(femaleInvestPropS,1,function(x) x*(10/sum(x))))
  
  #Some models can produce NaNs. This just converts these to 0
  maleInvestPropS[is.nan(maleInvestPropS)]<-0
  femaleInvestPropS[is.nan(femaleInvestPropS)]<-0
}

#Determine which female each male has chosen
#Break ties randomly
mchoice<-data.frame("male"=1:nrow(males))
mchoice$choice<-apply(maleInvestPropS,1,function(x) which.max(x))

#Determine which male each female has chosen
#Break ties randomly
fchoice<-data.frame("female"=1:nrow(females))
fchoice$choice<-apply(femaleInvestPropS,1,function(x) which.max(x))

#Loop through females' choices
for(p in 1:nrow(fchoice)){
  #Determine the male chosen by the current focal female
  chosenmale<-fchoice$choice[p]
  
  #Determine the female chosen by the focal female's choice
  chosenfemale<-mchoice$choice[chosenmale]
  
  #If the chosen female is the focal female...
  if(chosenfemale==p){
    #Pair the male and female together
    indPairs<-rbind(indPairs,cbind(females[p,],males[chosenmale,]))
  }
  
  #Otherwise do nothing
  
}

#Remove the row of NAs from the indPairs dataframe
indPairs<-indPairs[-1,]
    


######Calculating Couple Simulation Accuracy######

#Determine the CINs of all guessed pairs
avRels<-data.frame("females"=avPairs[,1],"males"=avPairs[,463])
sexRels<-data.frame("females"=sexPairs[,1],"males"=sexPairs[,463])
indRels<-data.frame("females"=indPairs[,1],"males"=indPairs[,463])


#Store the mate guessed by each model for each agent for females
females$avGuess<-avRels$males[match(females$CIN,avRels$females)]
females$sexGuess<-sexRels$males[match(females$CIN,sexRels$females)]
females$indGuess<-indRels$males[match(females$CIN,indRels$females)]

#Do the same for males
males$avGuess<-avRels$females[match(males$CIN,avRels$males)]
males$sexGuess<-sexRels$females[match(males$CIN,sexRels$males)]
males$indGuess<-indRels$females[match(males$CIN,indRels$males)]


#Calculate the accuracy of guesses for females
females$avAcc<-ifelse(is.na(females$avGuess)==F,females$avGuess==females$CIN,F)
females$sexAcc<-ifelse(is.na(females$sexGuess)==F,females$sexGuess==females$CIN,F)
females$indAcc<-ifelse(is.na(females$indGuess)==F,females$indGuess==females$CIN,F)

males$avAcc<-ifelse(is.na(males$avGuess)==F,males$avGuess==males$CIN,F)
males$sexAcc<-ifelse(is.na(males$sexGuess)==F,males$sexGuess==males$CIN,F)
males$indAcc<-ifelse(is.na(males$indGuess)==F,males$indGuess==males$CIN,F)


#Relationship quality
data2<-rbind(females,males)

r1<-lmer(scale(qmi_sat)~avAcc+(1|CIN),data=data2)
r2<-lmer(scale(qmi_sat)~indAcc+(1|CIN),data=data2)

```






######Plots######
```{r}

#Create a dataframe for plotting model results
plotdata<-data.frame("model"=c("Avg. Prefs","Sex-Typical","Indiv. Prefs"),"acc"=colMeans(females[,466:468]))

#Bootstrap confidence intervals
plotdata$lci<-apply(females[,466:468],2,function(x) quantile(sapply(1:10000,function(y) mean(sample(x,replace=T))),.025))
plotdata$uci<-apply(females[,466:468],2,function(x) quantile(sapply(1:10000,function(y) mean(sample(x,replace=T))),.975))

accplot<-qplot(model,acc,data=plotdata,fill=model,geom="blank",xlab="Preference Model",ylab="Simulation Accuracy")+geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=lci,ymax=uci))+theme_gray(base_size=25)+theme(axis.text.x=element_text(angle=90,hjust=1),legend.position="none")


rqPlotdata<-data2[,c(3,455,466,468)]

rqPlotdata<-melt(rqPlotdata,id.vars=c("PIN","qmi_sat"))

rqPlot<-qplot(variable,qmi_sat,fill=value,data=rqPlotdata,xlab="Preference Model",ylab="Relationship Satisfaction (QMI)",geom="blank")+
  scale_fill_discrete(name="Simulation\nAccuracy",labels=c("Inccurate","Accurate"))+geom_violin(position=position_dodge(.9),width=1)+
  scale_x_discrete(labels=c("Consensual","Individual"))+
  geom_boxplot(position=position_dodge(.9),width=.1)+
  theme_grey(base_size=30)

if(sf==1){
  ggsave("Figures/CAREER1 Simulation Accuracy-s.tiff",accplot,width=6,height=6,units="in",dpi=100)
  
  ggsave("Figures/CAREER1 Satisfaction Plot.tiff",rqPlot,width=12,height=12,units="in",dpi=100)
}

```